server:
  port: 8989      #tomcat启动端口号
  jsp-servlet:
    init-parameters:
      development: true  #开启jsp的热部署
spring:
  profiles:
    active: dev   #激活测试文件
  mvc:
    view:
      prefix: /    #配置SpringBoot的视图解析器
      suffix: .jsp
  datasource:   #数据源
    type: org.apache.commons.dbcp.BasicDataSource #使用DBCP的连接池
    driver-class-name: com.mysql.jdbc.Driver #连接数据库的驱动
    url: jdbc:mysql://localhost:3306/kg  #连接数据库的URL
    username: root #连接数据库的用户名
    password: root #连接数据库的密码
mybatis:
  type-aliases-package: com.baizhi.entity  #起别名
  mapper-locations: classpath:com/baizhi/dao/*Mapper.xml #Mapper文件的注册

